### ISSUE TITLE
[UI] Manage containers dropdown menu hides behind frame

### ISSUE THREAD

**Issue by faandg** [cockpit-project/cockpit-podman#1396] opened 2023-09-06 13:49 UTC
It's annoying to get the drop down menu behind the panel/box element and get a scrollbar just to access it.
Might be possible to bring it to the foreground or give the border window a height adjustment to accommodate it?
Many other options as well.

![image](https://github.com/cockpit-project/cockpit-podman/assets/5772741/69550cfd-a69e-4e8f-9bf1-b52731cc5820)
![image](https://github.com/cockpit-project/cockpit-podman/assets/5772741/16b2052f-3865-456a-b2de-c72c437e6614)

**Comment by subhoghoshX** [comment] 2023-09-07 05:08
Duplicate of #1386. It was fixed in #1388.

**Closed** 2023-09-07 05:36 UTC
Labels: enhancement
