### ISSUE TITLE
Ability to modify integrations after creating a container.

### ISSUE THREAD

**Issue by Magicrafter13** [cockpit-project/cockpit-podman#1411] opened 2023-09-18 23:01 UTC
I think cockpit-podman desparately needs this - an edit button, right around here:
![image](https://github.com/cockpit-project/cockpit-podman/assets/29127566/75656d68-b397-4b1f-a15c-34018be263ee)
There are a few scenarios where this is useful, but here's my angle: cockpit and its addons make system administration easier, and they're especially great for warming up to new concepts. For me, though I can do most things from a terminal, containers are fairly new to me and my workflow - I'm used to doing everything "manually".

As such, it tends to take some experimenting to get these working (any that need file system or host port integrations). And when I find myself in this situation (say I put the wrong port number in), what I'm forced to do is delete the container, and re-create it (meaning I also need to remember the other settings I already gave it too...). In the best cases this is a minor inconvenience, but in the worst case this could mean losing a ton of data that the user may have no idea how to get out from the container (assuming they even can get it out - or even put it back in) - and I'm referring to containers for things such as GitLab for example - containers with big self managed data storage of some kind.

I did try manually editing the file(s) I found with the port numbers I wanted to change once, but apparently the files podman uses are check-summed, so I basically broke it and had to wipe all of its data...

**Comment by jelly** [comment] 2023-09-19 09:17
Thanks for opening this issue, this is a duplicate of https://github.com/cockpit-project/cockpit-podman/issues/1293

Containers in nature are immutable, they are not really meant to be edited by a user. In the issue above we do consider an "re-create" button as that is essentially what you are asking for.

**Closed by jelly** 2023-09-19 09:17 UTC
Labels: enhancement

**Comment by Magicrafter13** [comment] 2023-09-19 16:15
> Thanks for opening this issue, this is a duplicate of #1293
> 
> Containers in nature are immutable, they are not really meant to be edited by a user. In the issue above we do consider an "re-create" button as that is essentially what you are asking for.

Even if you cannot change the port on the container side, you should be able to change which port it is mapped to on the host side. Same with the mount locations.
