### ISSUE TITLE
Cockpit-Podman: Memory does not show memory

### ISSUE THREAD

**Issue by ne20002** [cockpit-project/cockpit-podman#776] opened 2021-09-30 16:35 UTC
Cockpit version: 251
OS: Debian Bullseye
Page: 
Podman

The column memory ('Speicher') is not showing memory used by a container, but the amount used and size of the system disk.

![grafik](https://user-images.githubusercontent.com/39007279/135495446-955bcd3c-fef7-4a4f-a14d-d87cc249f43e.png)

Memory of the Pod is 8GB, 16GB is size of primary (system) disk.

**Comment by KKoukiou** [comment] 2021-09-30 17:25
@ne20002 I think you are seeing https://github.com/cockpit-project/cockpit-podman/issues/756 

There is an open PR to solve this issue.

**Comment by marusak** [comment] 2021-10-05 08:56
Duplicate of https://github.com/cockpit-project/cockpit-podman/issues/756 - being fixed in https://github.com/cockpit-project/cockpit-podman/pull/773

**Closed by marusak** 2021-10-05 08:56 UTC
