### ISSUE TITLE
wrong translation in pt_BR po file

### ISSUE THREAD

**Issue by jfaltenbacher** [cockpit-project/cockpit-podman#1940] opened 2024-12-17 09:33 UTC
Hello,

In the Portuguese Brazil po file, there seems to be a wrong translation` 'Prune unused images'` is translated with `'Obter nova imagem'` (=Get new image)

see line 1110 in file [pt_BR](https://github.com/cockpit-project/cockpit-podman-weblate/blob/main/pt_BR.po) 

```
#: src/PruneUnusedImagesModal.jsx:90 src/Images.jsx:365
#, fuzzy
#| msgid "Get new image"
msgid "Prune unused images"
msgstr "Obter nova imagem"
```

Sorry, if this is the wrong place to report this. I first reported at [podman-weblate]( https://github.com/cockpit-project/cockpit-podman-weblate/issues/3) but that repository does not seem to be monitored.

**Comment by martinpitt** [comment] 2024-12-17 10:50
It's marked as "fuzzy", which means that it's not really active. When strings change, gettext just leaves them in place as starting point for translators. This string currently [does not occur in the code at all](https://translate.fedoraproject.org/projects/cockpit-podman/main/pt_BR/?q=%20source:%22Get%20new%20image%22%20#search), so it's just leftover.

So, not a bug. Thanks for checking though!

**Closed by martinpitt** 2024-12-17 10:50 UTC
Labels: bug

**Comment by jfaltenbacher** [comment] 2024-12-17 11:15
ok, thanks for the fast action and reply. One day, I'll remember the fuzzy part :)
