### ISSUE TITLE
Tests failed on 87d79954cb9d330a26364e8a2f04509db16c7f86

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit-podman#1745] opened 2024-06-04 02:08 UTC
The job `fedora-40/updates-testing` failed on commit 87d79954cb9d330a26364e8a2f04509db16c7f86.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-87d79954-20240604-015759-fedora-40-updates-testing/log.html

**Comment by martinpitt** [comment] 2024-06-04 04:28
Duplicate of #1733

**Closed by martinpitt** 2024-06-04 04:28 UTC
Labels: nightly
