### ISSUE TITLE
Tests failed on 1484e3313a9cbac4579d59b6da0e198b92e4d5ce

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit-podman#1761] opened 2024-06-19 02:09 UTC
The job `fedora-40/updates-testing` failed on commit 1484e3313a9cbac4579d59b6da0e198b92e4d5ce.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-1484e331-20240619-015952-fedora-40-updates-testing/log.html

**Comment by martinpitt** [comment] 2024-06-19 05:07
Duplicate of #1724

**Closed by martinpitt** 2024-06-19 05:07 UTC
Labels: nightly
