### ISSUE TITLE
Not working with fedora 33 v 233

### ISSUE THREAD

**Issue by boistordu** [cockpit-project/cockpit-podman#619] opened 2020-12-06 23:55 UTC
![image](https://user-images.githubusercontent.com/9523075/101296971-61727f00-381e-11eb-9cfd-21126948b003.jpeg)
![image](https://user-images.githubusercontent.com/9523075/101296986-6c2d1400-381e-11eb-90bb-d31d674946bd.jpeg)
Any ideas?

**Comment by marusak** [comment] 2020-12-10 08:54
What version of podman and cockpit-podman are you using?

**Comment by boistordu** [comment] 2020-12-10 19:46
The one available in the general repo. 
233.1-1.fc33
25-1.fc33 for cockpit podman 
Both like the rest are the ones in @updates 
And it s pretty standard installation so no need to ask me if I change anything etc this is just no the case

**Comment by marusak** [comment] 2020-12-13 18:35
You haven't provided `podman` version, which is the one, the can possibly break cockpit-podman. But seems you use Fedora 33 and the currently available podman versions all work as expected.

Can you please check this command for me?
```
sudo curl --unix-socket /run/podman/podman.sock http://d/v1.24/libpod/info
```

Also this one?
```
sudo curl --unix-socket /run/podman/podman.sock http://d/v1.24/events
```
This one should stay open (it won't print out anything, but will not finish) Then when you would do in some other terminal any podman action (like `podman run`) you should see something to appear in the first terminal.

Can you please provide output of both commands? Thanks.

**Comment by boistordu** [comment] 2020-12-14 11:32
sorry I didn't understand that you wanted also the version of podman.
And yeah pretty standard installation, I didn't build podman from sources or anything like that:
```
podman.x86_64                                     2:2.2.1-1.fc33                   @updates          
podman-plugins.x86_64                             2:2.2.1-1.fc33                   @updates   
```

```
$ sudo curl --unix-socket /run/podman/podman.sock http://d/v1.24/libpod/info
{"host":{"arch":"amd64","buildahVersion":"1.18.0","cgroupManager":"systemd","cgroupVersion":"v1","conmon":{"package":"conmon-2.0.21-3.fc33.x86_64","path":"/usr/bin/conmon","version":"conmon version 2.0.21, commit: 0f53fb68333bdead5fe4dc5175703e22cf9882ab"},"cpus":8,"distribution":{"distribution":"fedora","version":"33"},"eventLogger":"journald","hostname":"kvm67kdocker.ada","idMappings":{"gidmap":null,"uidmap":null},"kernel":"5.9.13-200.fc33.x86_64","memFree":387792896,"memTotal":16323194880,"ociRuntime":{"name":"runc","package":"containerd.io-1.4.3-3.1.fc33.x86_64","path":"/usr/bin/runc","version":"runc version 1.0.0-rc92\ncommit: ff819c7e9184c13b7c2607fe6c30ae19403a7aff\nspec: 1.0.2-dev"},"os":"linux","rootless":false,"slirp4netns":{"executable":"","package":"","version":""},"swapFree":20790894592,"swapTotal":21000871936,"uptime":"17h 56m 45.72s (Approximately 0.71 days)","linkmode":"dynamic"},"store":{"configFile":"/etc/containers/storage.conf","containerStore":{"number":0,"paused":0,"running":0,"stopped":0},"graphDriverName":"overlay","graphOptions":{"overlay.mountopt":"nodev,metacopy=on"},"graphRoot":"/var/lib/containers/storage","graphStatus":{"Backing Filesystem":"extfs","Native Overlay Diff":"false","Supports d_type":"true","Using metacopy":"true"},"imageStore":{"number":0},"runRoot":"/var/run/containers/storage","volumePath":"/var/lib/containers/storage/volumes"},"registries":{"search":["registry.fedoraproject.org","registry.access.redhat.com","registry.centos.org","docker.io"]},"version":{"APIVersion":"2.1.0","Version":"2.2.1","GoVersion":"go1.15.5","GitCommit":"","BuiltTime":"Tue Dec  8 15:37:50 2020","Built":1607438270,"OsArch":"linux/amd64"}}
```


command just to run a simple hello-world. as you can see totally functionnable.
```
 sudo curl --unix-socket /run/podman/podman.sock http://d/v1.24/events
{"Type":"system","Action":"refresh","Actor":{"ID":"","Attributes":{"containerExitCode":"0","image":"","name":""}},"scope":"local","time":1607945467,"timeNano":1607945467873313587}
{"Type":"image","Action":"pull","Actor":{"ID":"","Attributes":{"containerExitCode":"0","image":"","name":""}},"scope":"local","time":1607945471,"timeNano":1607945471717169440}
{"Type":"container","Action":"create","Actor":{"ID":"54206913c1872dbdcfe11e023668f2d8ce2c6bb6bdc60a3992f875dce3a0b3da","Attributes":{"containerExitCode":"0","image":"docker.io/library/hello-world:latest","name":"gifted_gates"}},"scope":"local","time":1607945471,"timeNano":1607945471804654585}
{"Type":"container","Action":"init","Actor":{"ID":"54206913c1872dbdcfe11e023668f2d8ce2c6bb6bdc60a3992f875dce3a0b3da","Attributes":{"containerExitCode":"0","image":"docker.io/library/hello-world:latest","name":"gifted_gates"}},"scope":"local","time":1607945471,"timeNano":1607945471892325012}
{"Type":"container","Action":"start","Actor":{"ID":"54206913c1872dbdcfe11e023668f2d8ce2c6bb6bdc60a3992f875dce3a0b3da","Attributes":{"containerExitCode":"0","image":"docker.io/library/hello-world:latest","name":"gifted_gates"}},"scope":"local","time":1607945471,"timeNano":1607945471916332504}
{"Type":"container","Action":"attach","Actor":{"ID":"54206913c1872dbdcfe11e023668f2d8ce2c6bb6bdc60a3992f875dce3a0b3da","Attributes":{"containerExitCode":"0","image":"docker.io/library/hello-world:latest","name":"gifted_gates"}},"scope":"local","time":1607945471,"timeNano":1607945471916393687}
{"Type":"container","Action":"died","Actor":{"ID":"54206913c1872dbdcfe11e023668f2d8ce2c6bb6bdc60a3992f875dce3a0b3da","Attributes":{"containerExitCode":"0","image":"docker.io/library/hello-world:latest","name":"gifted_gates"}},"scope":"local","time":1607945471,"timeNano":1607945471944411092}
{"Type":"container","Action":"cleanup","Actor":{"ID":"54206913c1872dbdcfe11e023668f2d8ce2c6bb6bdc60a3992f875dce3a0b3da","Attributes":{"containerExitCode":"0","image":"docker.io/library/hello-world:latest","name":"gifted_gates"}},"scope":"local","time":1607945472,"timeNano":1607945472009678614}
^C
```

**Comment by marusak** [comment] 2020-12-14 19:52
Hmmm, I am about to run out of ideas, but I have one more idea what coukd be the problem.
Do you log in as non-root user, right? Do you have limited access (see on the top, the right section).
If so, can you also check `systemctl --user status podman.socket` and `systemctl --user status podman.service`? (run these as normal user).

Also then you check those curl commands without the `sudo` part (run as normal user) and replace `/run/podman/podman.sock` with `/run/user/1000/podman/podman.sock`.

Just when collecting info, are there any errors in your browser console?

**Comment by boistordu** [comment] 2020-12-15 09:36
Top right it s admin access.

The user didn't have the right access to when it was docker for example in previous version so I had to add it. 
I m going to check it now if he has access to docker in place of with sudo and see if it changes anything.

`systemctl --user status podman.socket `
Says active listening and loaded no error 

`systemctl --user status podman.service`

Says inactive dead and loaded but now the tab in the interface works.
I didn't touch anything. Is it possible that it was because I didn't run it before ?

**Comment by marusak** [comment] 2020-12-16 17:40
I think this is broken due to https://github.com/containers/podman/issues/8751

**Comment by boistordu** [comment] 2020-12-23 15:00
I m not sure but it could be. But in my case  the problem has been resolved by using it the first time in CLI. Which means that at initialization something does not trigger as it should be.

**Comment by marusak** [comment] 2021-03-16 13:27
This is podman issue not cockpit one.
There were (still are) a lot of issues in podman about services.
Closing, if it still happens to you, I can help you find reproducer which we can send to podman team.

**Closed by marusak** 2021-03-16 13:27 UTC
