### ISSUE TITLE
BUG: unable to edit podman containers

### ISSUE THREAD

**Issue by KyleSanderson** [cockpit-project/cockpit-podman#1775] opened 2024-07-01 05:37 UTC
### Explain what happens

1. There's no way to clone, or edit pods / similar through cockpit. 
2. I know podmanhas reiterated their hatred for users, but portainer, unraid, etc recreate pods based on this. Podman was supposed to be better than Docker.
3. Not being able to edit ports is brutal, especially when cockpit doesn't grab the image ahead of time to populate what was present in the OCI layers (EXPOSE / storage / etc).

### Version of Cockpit

cockpit 309 / podman 83 / tukit 0.1.2

### Where is the problem in Cockpit?

Storage

### Server operating system

openSUSE

### Server operating system version

MicroOS Leap 6.0

### What browsers are you using?

Chrome

**Comment by jelly** [comment] 2024-07-01 07:29
Duplicate of https://github.com/cockpit-project/cockpit-podman/issues/1293

**Closed by jelly** 2024-07-01 07:29 UTC
Labels: bug
