### ISSUE TITLE
Tests failed on 51fec83245979802411b33fba05b83e53a1e22a0

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit-podman#1742] opened 2024-06-03 02:08 UTC
The job `fedora-40/updates-testing` failed on commit 51fec83245979802411b33fba05b83e53a1e22a0.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-51fec832-20240603-015917-fedora-40-updates-testing/log.html

**Comment by martinpitt** [comment] 2024-06-03 05:38
Duplicate of #1733

**Closed by martinpitt** 2024-06-03 05:38 UTC
Labels: nightly
