### ISSUE TITLE
Allow to re-configure pods on the fly

### ISSUE THREAD

**Issue by schopenhauer** [cockpit-project/cockpit-podman#518] opened 2020-08-23 20:17 UTC
Self-explanatory.

I would love to see the option to edit existing pods and re-deploy them on-the-fly with slight modifications to the parameters, e.g. environment variables, RAM limits, etc.

**Comment by marusak** [comment] 2020-08-24 13:28
pods don't have enviroment variables, not RAM limits. Maybe you meant "containers"? If so, then this would be duplicate of https://github.com/cockpit-project/cockpit-podman/issues/363

**Comment by schopenhauer** [comment] 2020-08-24 13:55
That's right. What I had in mind was a RAM limit, etc. per container.

**Comment by marusak** [comment] 2020-08-26 07:43
Ok, I consider this duplicate of #363 as we decided in #169 that we don't want to edit resources on live containers.

**Closed by marusak** 2020-08-26 07:43 UTC
Labels: question
