### ISSUE TITLE
--device arguments

### ISSUE THREAD

**Issue by caioolivv** [cockpit-project/cockpit-podman#1276] opened 2023-04-22 21:13 UTC
From what I've seen on Issues #544 and #728, there is no possible way to add --device arguments. Is this right? If so, is there any workaround or any plans on supporting this?

**Comment by marusak** [comment] 2023-05-10 07:18
Unfortunately there is no workaround from our UI. Only solution at this moment is to use commandline.
Regarding plans - This is not on the teams current priority list however we are happy to accept any contributions :)

Closing as duplicate of #544

**Closed by marusak** 2023-05-10 07:18 UTC
Labels: enhancement
