### ISSUE TITLE
Support for podman container restart policy, when run under user instead of system.

### ISSUE THREAD

**Issue by fbd-ss** [cockpit-project/cockpit-podman#1741] opened 2024-06-02 20:59 UTC
It would be nice to have the restart policy available when containers/pods are run under user, instead of system.

It would also be nice to have the unless-stopped option.

The option to have restart policy at the pod level, as well as the container level would be nice.

**Comment by martinpitt** [comment] 2024-06-03 05:39
This is a duplicate of #921 and #1372. You can configure this, but we don't support or recommend this.

**Closed by martinpitt** 2024-06-03 05:39 UTC
Labels: enhancement
