### ISSUE TITLE
Administrative access see Containers of other owners

### ISSUE THREAD

**Issue by chrismaster** [cockpit-project/cockpit-podman#1562] opened 2024-02-09 10:09 UTC
Running Fedora 39 a user in wheel group in cockpit sees his containers and the system containers. (Even when I choose Owner All in the filter on top)
Is it possible to list containers from other users?
For the normal user, cockpit shows only the containers of the  normal user, which is ok.

**Comment by martinpitt** [comment] 2024-02-09 10:13
This is a duplicate of #692 . Sorry, this isn't on the plan.

**Closed by martinpitt** 2024-02-09 10:13 UTC
Labels: enhancement
