### ISSUE TITLE
Tests failed on c9498b338f5ec0cd77e072e70d1013404212d0fe

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit-podman#1766] opened 2024-06-24 02:15 UTC
The job `fedora-40/podman-next` failed on commit c9498b338f5ec0cd77e072e70d1013404212d0fe.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-c9498b33-20240624-020102-fedora-40-podman-next/log.html

**Comment by martinpitt** [comment] 2024-06-24 05:43
Duplicate of #1724

**Closed by martinpitt** 2024-06-24 05:43 UTC
Labels: nightly
