### ISSUE TITLE
Tests failed on 6d50fa54caea0672ea1245a9028ff9435fa83793

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit-podman#1747] opened 2024-06-05 02:04 UTC
The job `fedora-40/updates-testing` failed on commit 6d50fa54caea0672ea1245a9028ff9435fa83793.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-6d50fa54-20240605-015736-fedora-40-updates-testing/log.html

**Comment by martinpitt** [comment] 2024-06-05 04:11
Duplicate of #1733

**Closed by martinpitt** 2024-06-05 04:11 UTC
Labels: nightly
