### ISSUE TITLE
Tests failed on d8c8a9f3c5d218f6281b172d41549b4f60278786

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit-podman#1736] opened 2024-06-01 02:08 UTC
The job `fedora-40/updates-testing` failed on commit d8c8a9f3c5d218f6281b172d41549b4f60278786.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-d8c8a9f3-20240601-020000-fedora-40-updates-testing/log.html

**Comment by martinpitt** [comment] 2024-06-03 05:38
Duplicate of #1733

**Closed by martinpitt** 2024-06-03 05:38 UTC
Labels: nightly
