### ISSUE TITLE
testCommitUser fails on updates-testing

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit-podman#1733] opened 2024-05-31 02:05 UTC
The job `fedora-40/updates-testing` failed on commit 19ffacf6e31bbcab58e02eb651b849a2bd210270.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-19ffacf6-20240531-015714-fedora-40-updates-testing/log.html

https://bugzilla.redhat.com/show_bug.cgi?id=2284131

**Comment by jelly** [comment] 2024-05-31 12:29
```
error: Failed to commit container test-sh0: parsing reference "TEST:foobar": repository name must be lowercase: Internal Server Error
```

**Comment by jelly** [comment] 2024-05-31 14:52
Turns out the API returns invalid JSON:
```
[{"Id":"641797c5e7514087785bfd65c1462ba74fd01fb6be8b35aec621ed36c6e39149","ParentId":"","RepoTags":["localhost/test-alpine:latest"],"RepoDigests":["localhost/test-alpine@sha256:4295e30b6f0b388a492f2579ed97fb4854eff17db584bc60185e8bf7c6dc0650"],"Created":1716402094,"Size":8120820,"SharedSize":0,"VirtualSize":8120820,"Labels":{"com.jitesoft.app.alpine.version":"3.20.0","com.jitesoft.build.arch":"amd64","com.jitesoft.build.platform":"linux/amd64","com.jitesoft.project.registry.uri":"registry.gitlab.com/jitesoft/dockerfiles/alpine","com.jitesoft.project.repo.issues":"https://gitlab.com/jitesoft/dockerfiles/alpine/issues","com.jitesoft.project.repo.type":"git","com.jitesoft.project.repo.uri":"https://gitlab.com/jitesoft/dockerfiles/alpine","io.artifacthub.package.alternative-locations":"oci://index.docker.io/jitesoft/alpine,oci://ghcr.io/jitesoft/alpine","io.artifacthub.package.logo-url":"https://jitesoft.com/favicon-96x96.png","io.artifacthub.package.readme-url":"https://gitlab.com/jitesoft/dockerfiles/alpine/-/raw/master/README.md","maintainer":"Johannes Tegnér \u003cjohannes@jitesoft.com\u003e","maintainer.org":"Jitesoft","maintainer.org.uri":"https://jitesoft.com","org.opencontainers.image.created":"2024-05-22T18:21:28+00:00","org.opencontainers.image.description":"Alpine linux","org.opencontainers.image.source":"https://gitlab.com/jitesoft/dockerfiles/alpine","org.opencontainers.image.vendor":"Jitesoft","org.opencontainers.image.version":"3.20.0"},"Containers":1,"Arch":"amd64","Digest":"sha256:4295e30b6f0b388a492f2579ed97fb4854eff17db584bc60185e8bf7c6dc0650","History":["localhost/test-alpine:latest"],"IsManifestList":false,"Names":["localhost/test-alpine:latest"],"Os":"linux"},{"Id":"56a9b5a744a674481a5c034fec45ebf470a58ab844cd0da4d26b89bd27df5e36","ParentId":"","RepoTags":["localhost/test-busybox:latest"],"RepoDigests":["localhost/test-busybox@sha256:c7b56b8f280b21e95075e82005eb273fa8524fbbc0f7d968fab438263f6b6dcc"],"Created":1702637698,"Size":3914442,"SharedSize":0,"VirtualSize":3914442,"Labels":null,"Containeencontainers.image.source":"https://gitlab.com/jitesoft/dockerfiles/alpine","org.opencontainers.image.vendor":"Jitesoft","org.opencontainers.image.version":"3.20.0"},"Containers":0,"Dangling":true,"Arch":"amd64","Digest":"sha256:ce600e6b858db5ad822b82d0bec40376e3edb970a6334b2582dcca7092bb6875","History":["docker.io/library/0d50a318bc3e21e426034b4a3aa466d1fd9a4b1d86efe8e3a0e0019c447f9762-tmp:latest"],"IsManifestList":false,"Os":"linux"}]
```

**Comment by jelly** [comment] 2024-05-31 14:55
Reported bad karma: https://bodhi.fedoraproject.org/updates/FEDORA-2024-c612accb0f

**Comment by jelly** [comment] 2024-05-31 15:15
> hmm wasn't this noticed on any of the cockpit revdep tests that are run on podman PRs? Or is this test not run in the podman revdep tests?
> 
> cc @mheon

They should be part of the revdeps tests. Recent PR shows it succeeded: https://artifacts.dev.testing-farm.io/89f5d6b9-1049-4399-b2a9-fa4c45f6644e/work-podman-userar0l9zaf/plans/cockpit-podman/podman-user/execute/data/guest/default-0/test/browser/user-1/output.txt

**Comment by lsm5** [comment] 2024-05-31 15:25
no failures seen on the podman [v5.1.0 PR](https://github.com/containers/podman/pull/22839)

**Comment by jelly** [comment] 2024-05-31 15:37
Opened https://bugzilla.redhat.com/show_bug.cgi?id=2284131 if I should provide debug logs of podman I would be happy to do that.

**Comment by Luap99** [comment] 2024-05-31 15:41
Is that reproducible without cockipit? It really makes no sense why this passes on main but not the release?

**Comment by Luap99** [comment] 2024-05-31 15:45
`,"Labels":null,"Containeencontainers.image.source":"htt` this is the broken part

It is not clear why but it seems to have merged two things here. It sets "Labels":null, but than start listing labels afterwards anyway and the first label looks wrong as well

**Comment by jelly** [comment] 2024-06-03 07:17
> Is that reproducible without cockipit? It really makes no sense why this passes on main but not the release?

I haven't tried to debug this with a script but so far yes only within Cockpit

**Comment by Luap99** [comment] 2024-06-03 09:03
Given it passes on the rev dep tests in podman I am really confused as of why you can reproduce this with cockpit.

Also it is not clear to me at all that this is a podman bug, it could also be very well a bug on the reader side that overwrites  the buffer somehow. Can add `--log-level trace` to the podman system service process? It should all everything we write in the response. So if it is wrong there than we know the bug must be in podman but if it is correct there it can still be podman although I would consider this super unlikely then.

**Comment by jelly** [comment] 2024-06-03 13:37
Add `--log-level trace`, here are the results [trace.log](https://github.com/user-attachments/files/15534581/trace.log)

**Comment by Luap99** [comment] 2024-06-03 14:16
> Add `--log-level trace`, here are the results [trace.log](https://github.com/user-attachments/files/15534581/trace.log)

And that was on failed run with the same error from above? Because I do not see broken json in there (hard to tell with the format in there bit definitely not the one you reported above).

**Comment by martinpitt** [comment] 2024-06-04 07:17
Some bisection:
 - current `fedora-40` image: works :heavy_check_mark:  (podman-5.0.3-1.fc40.x86_64, kernel-core-6.8.10-300.fc40.x86_64, containers-common-0.58.0-2.fc40.noarch, crun-1.15-1.fc40.x86_64)
 - updating *only* podman-5:5.1.0-1.fc40.x86_64 from updates-testing: fails :red_circle: 
 - updating *everything* from updates-testing fails the same way :red_circle: , see [last night's run](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-19ffacf6-20240531-015714-fedora-40-updates-testing/log) (I didn't run that locally)
 - Updating *only* podman-102:5.2.0~dev-1.20240603175703949751.main.634.02983c3d5.fc40.x86_64 from podman-next COPR: works :heavy_check_mark: . This explains why upstream PRs are fine, as this seems fixed in main. @Luap99 

This also rules out that it's somewhere outside of podman, like containers-common or crun.

I'll try to find a CLI reproducer today.

**Comment by Luap99** [comment] 2024-06-04 09:44
@martinpitt ack, thanks for checking. There is very little divergence between 5.1 and main at this point and I don't see why  the code would just return broken json like that. We did make changes to the mentioned endpoint but it was only adding new fields and the same changes are in main.
Also as @lsm5 pointed out the cokpit tests passed on the 5.1 PR https://github.com/containers/podman/pull/22839 and they also pass on other 5.1 PR's, e.g. https://github.com/containers/podman/pull/22890.
Thus I I have a hard time believing that this is actually caused by some code in the podman tree. I have no doubt that your analysis is correct but I maybe the cause is not in podman? Second you only point out fedora 40 here, so am I right to assume 5.1 on rawhide is fine then?


I guess the good news is that it reproduces reliably for you.

**Comment by baude** [comment] 2024-06-04 12:06
@martinpitt if youc an replicate with curl, that'd be fine too!

**Comment by martinpitt** [comment] 2024-06-04 13:00
... and staring at the frames further, the dropped frames split the accented char in "Tegnér" in the middle -- so possibly some UTF-8 validation stumbles this and discards stuff?

**Comment by baude** [comment] 2024-06-04 13:25
will you unblock the negative karma that was filed?

**Comment by jelly** [comment] 2024-06-04 13:54
> will you unblock the negative karma that was filed?

Done, https://bodhi.fedoraproject.org/updates/FEDORA-2024-c612accb0f

**Comment by martinpitt** [comment] 2024-06-05 06:33
Let's move the cockpit side of this bug to https://github.com/cockpit-project/cockpit/issues/19235#issuecomment-2148908017 -- this is actually quite old, and even cockpit's integration tests see this occasionally. The [journal](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-19ffacf6-20240531-015714-fedora-40-updates-testing/TestApplication-testCommitUser-fedora-40-127.0.0.2-3001-FAIL-1.log.gz) also sees that indicative message:
```
podman[11150]: @ - - [31/May/2024:02:04:12 +0000] "GET /v1.12/libpod/images/json? HTTP/1.1" 200 4537 "" ""
cockpit-ws[11114]: invalid non-UTF8 @data passed as text to web_socket_connection_send()
```

I created an unit test now which reproduces this, so we don't need to rely on this specific podman case -- the next version of containers, image refreshes, or podman build will change this again, so it's very (un)lucky to hit.

In the meantime, I sent a podman PR to work around this: PR #1748

**Closed** 2024-06-05 08:26 UTC
Labels: nightly
